on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 10 2-12/2 *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
        SKIP_UPDATED: '1'
