on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 0'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ secrets.COATL_BOT_GH_TOKEN }}
    - name: Create scoop config file
      shell: pwsh
      run: |
        $configPath = Join-Path $env:USERPROFILE ".config\scoop"
        $configFile = Join-Path $configPath "config.json"
        $null = New-Item -ItemType Directory -Path $configPath -Force
        @{
          private_hosts = @(@{
            match   = "https://files.inductiveautomation.com/*"
            headers = "Referer=https://inductiveautomation.com/"
          })
          last_update = (Get-Date -Format "o")
          scoop_branch = "master"
          scoop_repo   = "https://github.com/ScoopInstaller/Scoop"
        } | ConvertTo-Json -Depth 10 | Set-Content -Path $configFile
        Get-Content $configFile
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.COATL_BOT_GH_TOKEN }}
        SKIP_UPDATED: '1'
        USER_EMAIL: ${{ vars.COATL_BOT_GH_EMAIL }}
