on:
  pull_request:
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create scoop config file
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force $env:USERPROFILE\.config\scoop
        $scoopConfigFile = "$env:USERPROFILE\.config\scoop\config.json"
        $currentDate = Get-Date -Format "o"
        $scoopConfig = "{`"private_hosts`":[{`"match`":`"https://files.inductiveautomation.com/*`",`"headers`":`"Referer=https://inductiveautomation.com/`"}],`"last_update`":`"$currentDate`",`"scoop_branch`":`"master`",`"scoop_repo`":`"https://github.com/ScoopInstaller/Scoop`"}"
        New-Item $scoopConfigFile -ItemType file
        $scoopConfig | ConvertFrom-Json | ConvertTo-Json -Depth 100 | Set-Content $scoopConfigFile
        Get-Content $scoopConfigFile
    - name: PullRequestHandler
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
